language: java
jdk:
  - openjdk11

deploy:
  skip_cleanup: true
  script: echo "HToken" ${HEROKU_TOKEN} "HToken2" $HEROKU_TOKEN
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "react-java-bookstore"