spring:
  datasource:
    url: ${databaseUrl}
    username: ${username}
    password: ${password}
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  sql:
    init:
      platform: postgres